import { AdminTable as Table } from "../components/AdminTable";
import { Surface } from "../components/Primitives";
import type { DashboardAnalyticsSnapshot } from "../services/dashboardAnalyticsMock";
import { AnalyticsDetails, type AnalyticsSelection } from "./AnalyticsDetails";
import { ListOrdered, TrendingUp } from "lucide-react";

const number=(value:number,decimals=0)=>value.toLocaleString("zh-CN",{minimumFractionDigits:decimals,maximumFractionDigits:decimals});
const compactNumber=(value:number)=>value>=10_000?`${Math.round(value/1000)}k`:value>=1000?`${(value/1000).toFixed(1)}k`:number(value);

export function DashboardAnalytics({data,selection,onSelectionChange}:{data:DashboardAnalyticsSnapshot;selection:AnalyticsSelection|null;onSelectionChange:(selection:AnalyticsSelection|null)=>void}){
  const pv=data.daily.map(day=>day.pv);const uv=data.daily.map(day=>day.uv);const width=760,height=180;const plot={left:48,right:694,top:16,bottom:145};const maximum=Math.ceil(Math.max(1,...pv,...uv)/1000)*1000;
  const x=(index:number)=>plot.left+index*(plot.right-plot.left)/Math.max(1,data.daily.length-1);const y=(value:number)=>plot.top+(1-value/maximum)*(plot.bottom-plot.top);
  const points=(values:number[])=>values.map((value,index)=>`${x(index)},${y(value)}`).join(" ");const ticks=[maximum,Math.round(maximum/2),0];const last=data.daily[data.daily.length-1];
  const periodRange=`${data.periodStart} 00:00:00 至 ${data.periodEnd} 23:59:59`;
  const withRange = (value: Omit<AnalyticsSelection,"startDate"|"endDate">): AnalyticsSelection => ({...value,startDate:data.periodStart,endDate:data.periodEnd});
  return <>
    <Surface className="dashboard-traffic-panel"><div className="dashboard-section-header dashboard-section-header-row"><div><h2><TrendingUp/>用户访问与行为</h2><p>{periodRange} · 访问规模与变化 · 来源表：analyticsEvents</p></div><div className="dashboard-chart-legend"><span><i className="is-uv"/>周期 UV<strong>{number(data.uv)}</strong></span><span><i className="is-pv"/>周期 PV<strong>{number(data.pv)}</strong></span></div></div>
      <div className="dashboard-traffic-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="UV 与 PV 趋势">{ticks.map((tick,index)=>{const tickY=plot.top+index*(plot.bottom-plot.top)/2;return <g key={tick}><line x1={plot.left} y1={tickY} x2={plot.right} y2={tickY} className="dashboard-line-grid"/><text x={plot.left-8} y={tickY+3} textAnchor="end" className="dashboard-axis-label">{compactNumber(tick)}</text></g>;})}<polyline points={points(uv)} className="dashboard-uv-line"/><polyline points={points(pv)} className="dashboard-pv-line"/>{data.daily.map((day,index)=>{const showDate=data.daily.length<=7||index%5===0||index===data.daily.length-1;return <g key={day.date} role="button" tabIndex={0} className="dashboard-traffic-point" onClick={()=>onSelectionChange(withRange({kind:"pv",date:day.date}))} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onSelectionChange(withRange({kind:"pv",date:day.date}));}}}><circle cx={x(index)} cy={y(day.uv)} r="3" className="is-uv"><title>{day.date} UV：{number(day.uv)}</title></circle><circle cx={x(index)} cy={y(day.pv)} r="3" className="is-pv"><title>{day.date} PV：{number(day.pv)}</title></circle>{showDate&&<text x={x(index)} y={height-7} textAnchor="middle" className="dashboard-axis-label">{day.date.slice(5).replace("-","/")}</text>}</g>;})}{last&&<><text x={plot.right+10} y={y(last.uv)+3} className="dashboard-line-value is-uv">UV {number(last.uv)}</text><text x={plot.right+10} y={y(last.pv)+3} className="dashboard-line-value is-pv">PV {number(last.pv)}</text></>}</svg></div>
    </Surface>
    <Surface className="dashboard-behavior-panel"><div className="dashboard-section-header"><div><h2><ListOrdered/>关键行为排行</h2><p>{periodRange} · 按用户数与发生次数观察关键路径 · 来源表：analyticsEvents</p></div></div><Table rowKey="eventName" size="small" pagination={false} dataSource={data.behaviors} onRow={record=>({onClick:()=>onSelectionChange(withRange({kind:"behavior",behavior:record.name,eventName:record.eventName})),onKeyDown:event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onSelectionChange(withRange({kind:"behavior",behavior:record.name,eventName:record.eventName}));}},tabIndex:0,className:"dashboard-behavior-row"})} columns={[{title:"行为",dataIndex:"name"},{title:"用户数",dataIndex:"users",align:"right",render:(value:number)=>number(value)},{title:"次数",dataIndex:"count",align:"right",render:(value:number)=>number(value)},{title:"转化率",dataIndex:"conversion",align:"right",render:(value:number)=>`${value.toFixed(1)}%`},{title:"操作",key:"action",width:90,render:()=> <span className="dashboard-table-link">查看明细</span>}]}/></Surface>
    <AnalyticsDetails data={data} selection={selection} onChange={value=>onSelectionChange(value)} onClose={()=>onSelectionChange(null)}/>
  </>;
}
